### ISSUE TITLE
“In ca.” not a usual phrasing

### ISSUE THREAD

**Issue by robinwhittleton** [aedattilo/ford-madox-ford_the-fifth-queen#1]
https://github.com/aedattilo/ford-madox-ford_the-fifth-queen/blob/f760b488f69922c74883db136f7fba72aa3a6ed2/src/epub/text/colophon.xhtml#L29

I think I’d probably use “around” rather than “in ca.”. If you do want to keep it, then let’s change ca. to circa.

**Comment by aedattilo** [comment]
changed to "around" in commit 883a71d
