### ISSUE TITLE
Remove italics from melee

### ISSUE THREAD

**Issue by robinwhittleton** [aedattilo/ford-madox-ford_the-fifth-queen#2]
https://github.com/aedattilo/ford-madox-ford_the-fifth-queen/blob/f760b488f69922c74883db136f7fba72aa3a6ed2/src/epub/text/chapter-3-2.xhtml#LL13C18-L13C18

Melee isn’t a loan word with this spelling, so we can remove the italics.

**Comment by aedattilo** [comment]
Removed in commit cefa199. This is easier than a rebase to remove that commit entirely-- let me know if I need to do that instead
