### ISSUE TITLE
Missed italics removal for a quote

### ISSUE THREAD

**Issue by robinwhittleton** [aedattilo/ford-madox-ford_the-fifth-queen#3]
https://github.com/aedattilo/ford-madox-ford_the-fifth-queen/blob/f760b488f69922c74883db136f7fba72aa3a6ed2/src/epub/text/chapter-2-7.xhtml#LL162C2-L162C2

> Says he: ‘<i>Here are such weaponings.</i>

I guess this was missed in the italics removal in https://github.com/aedattilo/ford-madox-ford_the-fifth-queen/commit/0af809233513f44bbb5a1546d5c4cf4ad9f85ba2?

**Comment by aedattilo** [comment]
removed them in commit 0938332
