### ISSUE TITLE
A few longdesc problems

### ISSUE THREAD

**Issue by robinwhittleton** [aedattilo/ford-madox-ford_the-fifth-queen#5]
https://github.com/aedattilo/ford-madox-ford_the-fifth-queen/blob/f760b488f69922c74883db136f7fba72aa3a6ed2/src/epub/content.opf#L53

- impoversihed -> impoverished
- triolgy -> trilogy
- “she comes to notice of the king” -> “she comes to the notice of the king” maybe?
- Can we link the trilogy to the collection URL that’ll be created: https://standardebooks.org/collections/the-fifth-queen

**Comment by aedattilo** [comment]
changed each in commit 8cdc1b7
